### PR TITLE
Update livro.yaml

### PR DESCRIPTION
**Pull request by Yitzhak22**

### CODE REVIEW

**Comment by szabgab** [comment]
Why dd you close this?

**Comment by Yitzhak22** [comment]
It seems that I have misunderstood the meaning of the 'close pull request'
button.
---- Original Message ----

**Comment by szabgab** [comment]
That's possible. You should only close it if you think it is a mistake.
Otherwise just let me handle it. I'll accept the Pull-Request you send and that will automatically close it.
I am going to open the Pull-Requests you sent in the last hour or so.

**Comment by szabgab** [comment]
I have integrated all of the recent changes you sent. They should show up on https://kantoniko.com/ in about 20 minutes.

Merci muncho!

**Pull request merged**
